#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import OrderedDict
from pathlib import Path
from typing import Any

import yaml


LayerKey = tuple[int, int]


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(path)

    data = yaml.safe_load(path.read_text())
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping at top level")
    return data


def require_mapping(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a mapping")
    return value


def require_number(value: Any, label: str) -> int | float:
    if not isinstance(value, (int, float)):
        raise ValueError(f"{label} must be numeric")
    return value


def parse_layer_key(value: Any, *, label: str) -> LayerKey:
    if not isinstance(value, list) or len(value) != 2:
        raise ValueError(f"{label} must be a two-element list: [layer, datatype]")
    layer, datatype = value
    if not isinstance(layer, int) or not isinstance(datatype, int):
        raise ValueError(f"{label} must contain two ints: [layer, datatype]")
    if layer < 0 or datatype < 0:
        raise ValueError(f"{label} values must be non-negative")
    return layer, datatype


def get_render_layers(data: dict[str, Any]) -> dict[str, Any]:
    if "render_layers" in data:
        return require_mapping(data["render_layers"], "render_layers")

    output_layers = require_mapping(data.get("output_layers", {}), "output_layers")
    return require_mapping(output_layers.get("render", {}), "output_layers.render")


def to_plain_data(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: to_plain_data(val) for key, val in value.items()}
    if isinstance(value, list):
        return [to_plain_data(item) for item in value]
    return value


def generate_blendergds_config(render_layers: dict[str, Any]) -> OrderedDict[str, Any]:
    out: OrderedDict[str, Any] = OrderedDict()
    seen_layers: dict[LayerKey, str] = {}

    for name, spec_any in render_layers.items():
        if not isinstance(name, str) or not name:
            raise ValueError(f"Render layer name must be a non-empty string: {name!r}")

        spec = require_mapping(spec_any, f"render_layers.{name}")
        layer, datatype = parse_layer_key(
            spec.get("layer"), label=f"render_layers.{name}.layer"
        )
        z = require_number(spec.get("zmin"), f"render_layers.{name}.zmin")
        height = require_number(
            spec.get("thickness"), f"render_layers.{name}.thickness"
        )
        if height <= 0:
            raise ValueError(f"render_layers.{name}.thickness must be positive")

        key = (layer, datatype)
        if key in seen_layers:
            previous = seen_layers[key]
            raise ValueError(
                f"{name!r} and {previous!r} both use GDS layer/datatype "
                f"[{layer}, {datatype}]"
            )
        seen_layers[key] = name

        out[name] = {
            "index": layer,
            "type": datatype,
            "z": float(z),
            "height": float(height),
        }

    return out


def write_blendergds_config(path: Path, data: OrderedDict[str, Any], source: Path) -> None:
    header = (
        "# SPDX-FileCopyrightText: 2026\n"
        "#\n"
        "# SPDX-License-Identifier: GPL-3.0-or-later\n"
        "#\n"
        f"# Generated by scripts/aim_generate_blendergds_config.py from {source}\n"
        "# Do not edit by hand; update AIM render layer metadata instead.\n\n"
    )
    body = yaml.safe_dump(to_plain_data(data), sort_keys=False)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + body)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a BlenderGDS layer stack config from AIM render_layers.yaml."
        )
    )
    parser.add_argument(
        "--render-layers",
        required=True,
        type=Path,
        help="Path to configs/aim/render_layers.yaml or layer_registry.local.yaml",
    )
    parser.add_argument(
        "--output",
        required=True,
        type=Path,
        help="Path to write the BlenderGDS config YAML",
    )
    args = parser.parse_args()

    data = load_yaml(args.render_layers)
    render_layers = get_render_layers(data)
    blendergds_config = generate_blendergds_config(render_layers)
    write_blendergds_config(args.output, blendergds_config, args.render_layers)

    print(f"Generated {len(blendergds_config)} BlenderGDS layer entries")
    print(f"Wrote: {args.output}")


if __name__ == "__main__":
    main()
